Ext.define('Healthsurvey.healthsurvey.shared.com.app.model.health.SurveyAnswerModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "surveyAnswerId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "surveyAnswerName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "surveyAnswerDesc",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});