DROP TABLE IF EXISTS `art_table_field_details`;

CREATE TABLE `art_table_field_details` (
  `field_id` varchar(64) NOT NULL ,
  `table_id` varchar(64) NOT NULL ,
  `field_name` varchar(256) NOT NULL,
  `data_type` varchar(256) NOT NULL,
  `datatype_precision` varchar(45) DEFAULT NULL,
  `is_pkey` tinyint(1) NOT NULL DEFAULT '0',
  `is_null` tinyint(1) NOT NULL DEFAULT '1',
  `is_auto_inc` tinyint(1) NOT NULL DEFAULT '0',
  `is_unique` tinyint(1) NOT NULL DEFAULT '0',
  `is_fkey` tinyint(1) NOT NULL DEFAULT '0',
  `reff_key` varchar(256) DEFAULT NULL,
  `reff_table` varchar(256) DEFAULT NULL,
  `primary_display` tinyint(1) DEFAULT NULL,
  `default_value` varchar(256) DEFAULT NULL,
  `system_field` tinyint(1) NOT NULL DEFAULT '0',
  `column_sequence` varchar(256) DEFAULT NULL,
  `display_json` text,
  `project_id` varchar(256) NOT NULL,
  `app_creator_id` varchar(256) NOT NULL,
  `project_version_id` varchar(256) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `version_id` int(11) DEFAULT NULL,
  `active_status` tinyint(1) DEFAULT '1',
  `field_order` int(5) DEFAULT NULL,
  `field_group` varchar(256) DEFAULT NULL,
  `target_field` varchar(256) DEFAULT NULL,
  `transient_field` tinyint(1) DEFAULT NULL,
  `ui_permission` int(10) DEFAULT '0',
  PRIMARY KEY (`field_id`),
  UNIQUE KEY `UNIQUE` (`table_id`,`field_name`),
  CONSTRAINT `FK` FOREIGN KEY (`table_id`) REFERENCES `art_table_details` (`table_id`)
);

