DROP TABLE IF EXISTS `zen_health`;

CREATE TABLE `zen_health` (
  `monitor_id` varchar(64) NOT NULL ,
  `class_Unloaded` int(11) NOT NULL,
  `gc_Collection_Time` int(11) NOT NULL,
  `non_Heap_Committed` bigint(20) NOT NULL,
  `start_Time` datetime NOT NULL,
  `cpu_Time` double NOT NULL,
  `cpu_Load_Time` double NOT NULL DEFAULT '0',
  `non_Heap_used` bigint(20) NOT NULL,
  `up_Time` int(11) NOT NULL,
  `free_Physical_Size` bigint(20) NOT NULL,
  `total_Thread` double NOT NULL,
  `heap_Committed` bigint(20) NOT NULL,
  `total_Physical_Memory_Size` bigint(20) NOT NULL,
  `thread_Peak_Count` double NOT NULL,
  `scheduled_DateTime` datetime NOT NULL,
  `max_Memory` bigint(20) NOT NULL,
  `cpu_Load` double NOT NULL DEFAULT '0',
  `thread_Started_Count` double NOT NULL,
  `thread_Daemon_Count` double NOT NULL,
  `server_Instance_Id` int(32) NOT NULL,
  `total_Class` varchar(256) NOT NULL,
  `free_Memory` bigint(20) NOT NULL,
  `free_Swap_Size` bigint(20) NOT NULL,
  `server_Ip_Address` varchar(30) NOT NULL,
  `class_Loaded` varchar(32) NOT NULL,
  `heap_Used` bigint(20) NOT NULL,
  `system_Load_Average` double NOT NULL,
  `thread_Cpu_Time` double NOT NULL,
  `total_Memory` bigint(20) NOT NULL,
  `total_Swap_Size` bigint(20) NOT NULL,
  `available_Processor` double NOT NULL,
  `gc_Memory_Name` varchar(256) NOT NULL,
  `thread_User_Time` varchar(45) DEFAULT NULL,
  `used_Memory` bigint(20) DEFAULT NULL,
  `used_Swap_Size` bigint(20) DEFAULT NULL,
  `used_Physical_Memory` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`monitor_id`)
);

